### ISSUE TITLE
集市出现异常

### ISSUE THREAD

**Issue by frostime** [RQYOU/SiYuan-Theme-Hazy-Moonlight#1]
打开集市之后，会疯狂报错，且 icon 和 preview.png 都加载不出来

![image](https://github.com/RQYOU/SiYuan-Theme-Hazy-Moonlight/assets/27268127/fef00d84-0be4-4d02-952b-e9beb6605803)

----

目测原因是这个仓库下找不到对应版本的 release。请仿照[官方样例](https://github.com/siyuan-note/theme-sample)，建立一个同版本的 release，并上传 package.zip，以方便仓库查询到主题的基本信息。

![image](https://github.com/RQYOU/SiYuan-Theme-Hazy-Moonlight/assets/27268127/b6d240b3-e6aa-4871-b7d9-846faa779289)

**Comment by RQYOU** [comment]
你好，抱歉，刚刚重新发布了 release。请查看一下现在是否正常了，谢谢！

发件人: Frostime ***@***.***>
日期: 星期四, 2023年7月6日 19:30
收件人: RQYOU/SiYuan-Theme-Hazy-Moonlight ***@***.***>
抄送: Subscribed ***@***.***>
主题: [RQYOU/SiYuan-Theme-Hazy-Moonlight] 集市出现异常 (Issue #1)

打开集市之后，会疯狂报错，且 icon 和 preview.png 都加载不出来

[图像已被发件人删除。 image]<https://user-images.githubusercontent.com/27268127/251436457-fef00d84-0be4-4d02-952b-e9beb6605803.png>

________________________________

目测原因是这个仓库下找不到对应版本的 release。请仿照官方样例<https://github.com/siyuan-note/theme-sample>，建立一个同版本的 release，并上传 package.zip，以方便仓库查询到主题的基本信息。

[图像已被发件人删除。 image]<https://user-images.githubusercontent.com/27268127/251436855-b6d240b3-e6aa-4871-b7d9-846faa779289.png>

―

**Comment by frostime** [comment]
目前已经正常显示，感谢修复
